
// ADDING 2 NUMBER WITHOUT CREATING VARIABLE TO GET 8 //
console.log(5+3);

//SUBTRACTING 2 NUMBERS WITHOUT CREATING VARIABLE TO GET 8  //
console.log(13-5);

//MULTIPLICATING 2 NUMBERS WITHOUT CREATING VARIABLE TO GET 8 //
console.log(2*4);
  
//DIVIDING 2 NUMBERS WITHOUT CREATING VARIABLE TO GET 8 //
console.log(16/2);